### ISSUE TITLE
[Bug] Calling Numerical.count_noun() results in exception nearly every time

### ISSUE THREAD

**Issue by tayjaybabee** [tayjaybabee/Inspyre-Toolbox#22]
The way the argument sanity and validity is checked results in an exception. 

```shell
num=Numerical(22)
num.count_noun('banana')
If passing a noun alone to 'count_noun' you need to include the parameter name
For example:
number.count_noun(noun='banana')
NOT
number.count_noun('banana')
Traceback (most recent call last):
  File "/home/taylor/Projects/Inspyre-Toolbox/inspyre_toolbox/humanize/__init__.py", line 303, in count_noun
    number = float(number)
ValueError: could not convert string to float: 'banana'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/taylor/.cache/pypoetry/virtualenvs/inspyre-toolbox-NRLqoI3d-py3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-63e7445e366f>", line 1, in <module>
    num.count_noun('banana')
  File "/home/taylor/Projects/Inspyre-Toolbox/inspyre_toolbox/humanize/__init__.py", line 315, in count_noun
    raise ValueError(warning)
ValueError: If passing a noun alone to 'count_noun' you need to include the parameter name
For example:
number.count_noun(noun='banana')
NOT
number.count_noun('banana')
num.count_noun(noun='banana')
Traceback (most recent call last):
  File "/home/taylor/.cache/pypoetry/virtualenvs/inspyre-toolbox-NRLqoI3d-py3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-10d8976b9158>", line 1, in <module>
    num.count_noun(noun='banana')
  File "/home/taylor/Projects/Inspyre-Toolbox/inspyre_toolbox/humanize/__init__.py", line 338, in count_noun
    ret = self.__count_noun(count=self.__number, noun=self.__noun, **kwargs)
  File "/home/taylor/Projects/Inspyre-Toolbox/inspyre_toolbox/humanize/__init__.py", line 456, in __count_noun
    raise ValueError("Noun must be of type: str")
ValueError: Noun must be of type: str
```

**Comment by tayjaybabee** [comment]
Fixed in commit 9b63eb5
